services:
  - type: web
    name: bybit-analyzer-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_SECRET_KEY
        sync: false
